## Basic Numpy

In [2]:
# Installation and Importing
import numpy as np

In [2]:
# Creating Arrays
a = np.array([1, 2, 3, 4, 5])
print(a)

print("\n" + "*" * 15 + "\n")

b = np.arange(0, 10, 2) # evenly spaced values within a specified range, with a given step size
print(b)

print("\n" + "*" * 15 + "\n")

c = np.linspace(0, 1, 5) # evenly spaced values between start and stop, inclusive
print(c)

[1 2 3 4 5]

***************

[0 2 4 6 8]

***************

[0.   0.25 0.5  0.75 1.  ]


In [3]:
# Creating Arrays with random values
d = np.random.randint(10,2000,12)
print(d)

print("\n" + "*" * 15 + "\n")

e = np.random.rand(3,3) #Random numbers in ndarrays
print(e)

print("\n" + "*" * 15 + "\n")

f = np.random.uniform(10,200,5)
print(f)

[ 751 1656  494  916  452 1975  958  419  983 1820  539  450]

***************

[[0.2127458  0.26602826 0.28714852]
 [0.75504961 0.10932292 0.64466944]
 [0.69502015 0.18539126 0.21413915]]

***************

[148.04832435  61.53975199 165.19106006  60.7034877  120.05562737]


In [4]:
# Creating Arrays with fixed values
g = np.full((2,3),6) # create an array filled with any given value using the np.full() method
print(g)

print("\n" + "*" * 15 + "\n")

h = np.zeros((3, 4))
print (h)

print("\n" + "*" * 15 + "\n")

i = np.ones((2,3,4))
print(i)

print("\n" + "*" * 15 + "\n")

j = np.eye(4) #np.eye() that returns an array with 1s along its diagonal and 0s everywhere else.
print(j)

[[6 6 6]
 [6 6 6]]

***************

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

***************

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

***************

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Unique values and repeating values
k = np.unique(a)
print(k)

print("\n" + "*" * 15 + "\n")

t = np.tile(a, 2) # repeats a given array along specified axes
print(t)

print("\n" + "*" * 15 + "\n")

u = np.repeat(a, 3) # repeats elements of an array
print(u)

In [5]:
# Basic info about numpy array
l = np.random.randint(10,2000,12).reshape(3,4)
print(l)

print("\n" + "*" * 15 + "\n")

print(l.ndim)

print("\n" + "*" * 15 + "\n")

print(l.shape)

print("\n" + "*" * 15 + "\n")

print(l.size) # total number of elements of the array

print("\n" + "*" * 15 + "\n")

print(l.itemsize) #the size in bytes of each element of the array. same sa : => arr2.dtype.itemsize

print("\n" + "*" * 15 + "\n")

print(l.dtype)

[[1433  779 1277  911]
 [1462 1326 1449 1782]
 [1865  183 1713 1461]]

***************

2

***************

(3, 4)

***************

12

***************

4

***************

int32


In [6]:
# Comparision in Arrays
print(a < 5)
      
print("\n" + "*" * 15 + "\n")
      
print(b > 5)
      
print("\n" + "*" * 15 + "\n")
      
print(c <= 5)
      
print("\n" + "*" * 15 + "\n")
      
print(d >= 5)
      
print("\n" + "*" * 15 + "\n")
      
print(e != 5)
      
print("\n" + "*" * 15 + "\n")
      
print(f == 5)

[ True  True  True  True False]

***************

[False False False  True  True]

***************

[ True  True  True  True  True]

***************

[ True  True  True  True  True  True  True  True  True  True  True  True]

***************

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

***************

[False False False False False]


In [7]:
# Basic Array Operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

a = x + y
b = y - x
c = x * y
d = x / y
e = x // y
f = x ** y
print("Addition : " a)

print("\n" + "*" * 15 + "\n")

print("Substraction : " b)

print("\n" + "*" * 15 + "\n")

print("Multiplication : " c)

print("\n" + "*" * 15 + "\n")

print("Division : " d)

print("\n" + "*" * 15 + "\n")

print("Floor division : "e)

print("\n" + "*" * 15 + "\n")

print("Power : " f)

[5 7 9]

***************

[3 3 3]

***************

[ 4 10 18]

***************

[0.25 0.4  0.5 ]

***************

[0 0 0]

***************

[  1  32 729]


In [4]:
# Array Indexing and Slicing
m = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[11, 12, 13], [14, 15, 16], [17, 18, 19]]])
print(m)

print("\n" + "*" * 15 + "\n")\

print(m[1,2])

print("\n" + "*" * 15 + "\n")

print(m[-1])

print("\n" + "*" * 15 + "\n")

print(m[0:1,2])   

print("\n" + "*" * 15 + "\n")

print(m[:,1])   # Access all elements in row 1

print("\n" + "*" * 15 + "\n")

print(m[1:4,[0,2]]) # using advanced index for column

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]

***************

[17 18 19]

***************

[[11 12 13]
 [14 15 16]
 [17 18 19]]

***************

[[7 8 9]]

***************

[[ 4  5  6]
 [14 15 16]]

***************

[[[11 12 13]
  [17 18 19]]]


In [9]:
# Array Shape and Reshaping
n = np.arange(8).reshape(2, 4)
print(n)

print("\n" + "*" * 15 + "\n")

o = np.shape(a)
print(o)

print("\n" + "*" * 15 + "\n")

p = np.resize(a,(8,1))
print(p)

print("\n" + "*" * 15 + "\n")

q = np.reshape(a,(4,-1)) # -1 if we do not know columns
print(q)

[[0 1 2 3]
 [4 5 6 7]]

***************

(2, 4)

***************

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]

***************

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [10]:
# Basic Functions and Operations
r = np.array([[[1, 2], [3, 4]], [[11, 22], [33, 44]]])
print(r)

print("\n" + "*" * 15 + "\n")

print(np.sum(r))   

print("\n" + "*" * 15 + "\n")

print(np.mean(r, axis=0))   

print("\n" + "*" * 15 + "\n")

print(np.std(r))     

print("\n" + "*" * 15 + "\n")

print(np.min(r, axis=0))   

print("\n" + "*" * 15 + "\n")

print(np.max(r, axis=1))       

[[[ 1  2]
  [ 3  4]]

 [[11 22]
  [33 44]]]

***************

120

***************

[[ 6. 12.]
 [18. 24.]]

***************

15.247950681976906

***************

[[1 2]
 [3 4]]

***************

[[ 3  4]
 [33 44]]


In [11]:
# Basic Functions and Operations
s = np.array([[[1, 2], [3, 4]], [[11, 22], [33, 44]]])
print(s)

print("\n" + "*" * 15 + "\n")

print(np.sqrt(s))   

print("\n" + "*" * 15 + "\n")

print(np.exp(s))   

print("\n" + "*" * 15 + "\n")

print(np.sin(s))     

print("\n" + "*" * 15 + "\n")

print(np.cos(s))   

[[[ 1  2]
  [ 3  4]]

 [[11 22]
  [33 44]]]

***************

[[[1.         1.41421356]
  [1.73205081 2.        ]]

 [[3.31662479 4.69041576]
  [5.74456265 6.63324958]]]

***************

[[[2.71828183e+00 7.38905610e+00]
  [2.00855369e+01 5.45981500e+01]]

 [[5.98741417e+04 3.58491285e+09]
  [2.14643580e+14 1.28516001e+19]]]

***************

[[[ 0.84147098  0.90929743]
  [ 0.14112001 -0.7568025 ]]

 [[-0.99999021 -0.00885131]
  [ 0.99991186  0.01770193]]]

***************

[[[ 0.54030231 -0.41614684]
  [-0.9899925  -0.65364362]]

 [[ 0.0044257  -0.99996083]
  [-0.01327675  0.99984331]]]


In [12]:
# Maximum value index
t = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])

max_index = np.argmax(t) # Find the index of the maximum value

print("Original Array:", t)
print("Index of Maximum Value:", max_index)

Original Array: [3 1 4 1 5 9 2 6 5]
Index of Maximum Value: 5
