## Intermediate Numpy

In [2]:
import numpy as np

In [2]:
# Transforming Arrays
a = np.arange(1,900,30).reshape(5,6)
print("a : "+ "\n",a)

print("\n" + "*" * 15 + "\n") # Cosmetics

b = np.transpose(a) # transpose of a NumPy array
print("Transpose : "  + "\n", b)

print("\n" + "*" * 15 + "\n") # Cosmetics

c = a.flatten() # Flatten the array
print("Flatten : " + "\n", c)

print("\n" + "*" * 15 + "\n") # Cosmetics

z = np.array([[[1,2],[3,4]]])
d = np.squeeze(z, axis = 0) # remove dimensions with size 1, potentially altering the shape of the array
print("z" + "\n", z)
print("\n" + "*" * 15 + "\n") # Cosmetics
print("Squeeze : "  + "\n", d)

print("\n" + "*" * 15 + "\n") # Cosmetics
print("a : "+ "\n",a)
print("\n" + "*" * 15 + "\n") # Cosmetics

e = np.flip(a,axis=1) # flip axis
print("Flip : "  + "\n", e)

print("\n" + "*" * 15 + "\n") # Cosmetics

f = np.rollaxis(a,1) # to roll a axis
print("Roll axix : "  + "\n", f)

print("\n" + "*" * 15 + "\n") # Cosmetics

h = np.swapaxes(a, 1, 0) # to swap axis
print("Swap axis : " + "\n", h)

a : 
 [[  1  31  61  91 121 151]
 [181 211 241 271 301 331]
 [361 391 421 451 481 511]
 [541 571 601 631 661 691]
 [721 751 781 811 841 871]]

***************

Transpose : 
 [[  1 181 361 541 721]
 [ 31 211 391 571 751]
 [ 61 241 421 601 781]
 [ 91 271 451 631 811]
 [121 301 481 661 841]
 [151 331 511 691 871]]

***************

Flatten : 
 [  1  31  61  91 121 151 181 211 241 271 301 331 361 391 421 451 481 511
 541 571 601 631 661 691 721 751 781 811 841 871]

***************

z
 [[[1 2]
  [3 4]]]

***************

Squeeze : 
 [[1 2]
 [3 4]]

***************

a : 
 [[  1  31  61  91 121 151]
 [181 211 241 271 301 331]
 [361 391 421 451 481 511]
 [541 571 601 631 661 691]
 [721 751 781 811 841 871]]

***************

Flip : 
 [[151 121  91  61  31   1]
 [331 301 271 241 211 181]
 [511 481 451 421 391 361]
 [691 661 631 601 571 541]
 [871 841 811 781 751 721]]

***************

Roll axix : 
 [[  1 181 361 541 721]
 [ 31 211 391 571 751]
 [ 61 241 421 601 781]
 [ 91 271 451 631 811]
 [1

In [3]:
#Advanced Indexing and slicing

m = np.array([[1, 2], [3, 4], [5, 6]]) 
n = m[[0,1,2], [0,1,0]] # (0,0), (1,1) and (2,0)
o = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])

p = [m > 5] # boolean Array Indexing
print("Boolean indexing : "  + "\n", p)

print("\n" + "*" * 15 + "\n") # Cosmetics

q = np.array([1, 2, 3, 4, 5, 6])
r = np.clip(q, 2, 4)
print("clip : "  + "\n", r)


Boolean indexing : 
 [array([[False, False],
       [False, False],
       [False,  True]])]

***************

clip : 
 [2 2 3 4 4 4]


In [6]:
# Stacking and Splitting
s = np.array([[1,2],[3,4],[11,12],[21,22]])
print(s)

print("\n" + "*" * 15 + "\n") # Cosmetics

t = np.array([[5,6],[7,8],[15,16],[25,26]])
print(t)

print("\n" + "*" * 15 + "\n") # Cosmetics

u = np.vstack((s,t))
print("vstack : " + "\n", u)

print("\n" + "*" * 15 + "\n") # Cosmetics

v = np.hstack((s,t))
print("hstack : " + "\n", v)

print("\n" + "*" * 15 + "\n") # Cosmetics

w = np.split(s, 2)
print("split : " + "\n", w)

print("\n" + "*" * 15 + "\n") # Cosmetics

x = np.vsplit(s, 4)
print("vsplit : " + "\n", x)

print("\n" + "*" * 15 + "\n") # Cosmetics

y = np.hsplit(t, 2)
print("hsplit : " + "\n", y)

[[ 1  2]
 [ 3  4]
 [11 12]
 [21 22]]

***************

[[ 5  6]
 [ 7  8]
 [15 16]
 [25 26]]

***************

vstack : 
 [[ 1  2]
 [ 3  4]
 [11 12]
 [21 22]
 [ 5  6]
 [ 7  8]
 [15 16]
 [25 26]]

***************

hstack : 
 [[ 1  2  5  6]
 [ 3  4  7  8]
 [11 12 15 16]
 [21 22 25 26]]

***************

split : 
 [array([[1, 2],
       [3, 4]]), array([[11, 12],
       [21, 22]])]

***************

vsplit : 
 [array([[1, 2]]), array([[3, 4]]), array([[11, 12]]), array([[21, 22]])]

***************

hsplit : 
 [array([[ 5],
       [ 7],
       [15],
       [25]]), array([[ 6],
       [ 8],
       [16],
       [26]])]


In [5]:
# Array values manipulation
a = np.array([[[1, 2], [3, 4]],[[1, 2], [3, 4]]])
print("a : " + "\n", a)

print("\n" + "*" * 15 + "\n")

b = np.append(a, [[[11, 12], [13, 14]],[[5, 16], [17, 18]]])
print("append : " + "\n", b)

print("\n" + "*" * 15 + "\n") # Cosmetics

c = np.array([[1,2],[3,4],[5,6]])
print("c : " + "\n", c)

print("\n" + "*" * 15 + "\n") # Cosmetics

d = np.insert(c,3,[11,12])
print("insert : " + "\n", d)

print("\n" + "*" * 15 + "\n") # Cosmetics

e = np.insert(c,1,[11,12],axis = 0) 
print("insert : " + "\n", e)

print("\n" + "*" * 15 + "\n") # Cosmetics

print("c : " + "\n", c)
f = np.delete(c,3) # array flattened before delete operation as axis not used
print("delete : " + "\n", f)

print("\n" + "*" * 15 + "\n") # Cosmetics

print("c : " + "\n", c)
g = np.delete(c,1, axis = 1)
print("delete : " + "\n", g)

print("\n" + "*" * 15 + "\n") # Cosmetics

print("s : " + "\n", s)
print("t : " + "\n", t)

print("\n" + "*" * 15 + "\n") # Cosmetics

combined = np.concatenate((s, t))
print("cocatenate" + "\n", combined)

a : 
 [[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]

***************

append : 
 [ 1  2  3  4  1  2  3  4 11 12 13 14  5 16 17 18]

***************

c : 
 [[1 2]
 [3 4]
 [5 6]]

***************

insert : 
 [ 1  2  3 11 12  4  5  6]

***************

insert : 
 [[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]

***************

c : 
 [[1 2]
 [3 4]
 [5 6]]
delete : 
 [1 2 3 5 6]

***************

c : 
 [[1 2]
 [3 4]
 [5 6]]
delete : 
 [[1]
 [3]
 [5]]

***************

s : 
 [[ 1  2]
 [ 3  4]
 [11 12]
 [21 22]]
t : 
 [[ 5  6]
 [ 7  8]
 [15 16]
 [25 26]]

***************

cocatenate
 [[ 1  2]
 [ 3  4]
 [11 12]
 [21 22]
 [ 5  6]
 [ 7  8]
 [15 16]
 [25 26]]


In [6]:
# Matrix opertions
h = np.array([[[1, 2], [3, 4]],[[11, 12], [13, 14]]])
print("h : " + "\n", h)

print("\n" + "*" * 15 + "\n") # Cosmetics

i = np.array([[[5, 6], [7, 8]],[[15, 16], [17, 18]]])
print("i : " + "\n", i)

print("\n" + "*" * 15 + "\n") # Cosmetics

j = np.dot(h, i)   # matrix multiplication
print("Dot product : " + "\n", j)

print("\n" + "*" * 15 + "\n") # Cosmetics

k = np.cross(h, i)
print("Cross product : " + "\n", k)

print("\n" + "*" * 15 + "\n") # Cosmetics

l = np.linalg.inv(h)
print("Inverse : " + "\n", l)

print("\n" + "*" * 15 + "\n") # Cosmetics

m = np.linalg.det(h)
print("Determinant : " + "\n", m)

h : 
 [[[ 1  2]
  [ 3  4]]

 [[11 12]
  [13 14]]]

***************

i : 
 [[[ 5  6]
  [ 7  8]]

 [[15 16]
  [17 18]]]

***************

Dot product : 
 [[[[ 19  22]
   [ 49  52]]

  [[ 43  50]
   [113 120]]]


 [[[139 162]
   [369 392]]

  [[163 190]
   [433 460]]]]

***************

Cross product : 
 [[-4 -4]
 [-4 -4]]

***************

Inverse : 
 [[[-2.   1. ]
  [ 1.5 -0.5]]

 [[-7.   6. ]
  [ 6.5 -5.5]]]

***************

Determinant : 
 [-2. -2.]


In [7]:
# Linear Algebra
nn = np.array([[1, 2], [3, 4]])
mm = np.array([[0, -3], [0.5, -0.1]])
eigenvalues, eigenvectors = np.linalg.eig(nn)

print("Eigenvalues:" + "\n", eigenvalues)

print("\n" + "*" * 15 + "\n") # Cosmetics

print("Eigenvectors:" + "\n", eigenvectors)

print("\n" + "*" * 15 + "\n") # Cosmetics

correlation_coefficient = np.corrcoef(nn,mm)

print("Correlation Coefficient:" + "\n", correlation_coefficient)
# correlation_coefficient[0, 1] represents the correlation between the first column of n and the second column of m

Eigenvalues:
 [-0.37228132  5.37228132]

***************

Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

***************

Correlation Coefficient:
 [[ 1.  1. -1. -1.]
 [ 1.  1. -1. -1.]
 [-1. -1.  1.  1.]
 [-1. -1.  1.  1.]]


In [8]:
# Normalize an array
z = np.array([1, 2, 3, 4, 5])
normalized_array = z / np.linalg.norm(z)
print("Normalized array:" +"\n", normalized_array)

Normalized array:
 [0.13483997 0.26967994 0.40451992 0.53935989 0.67419986]


In [9]:
# Solve linear equation

# 2x+3y=8 & 5x−2y=−7
a = np.array([[2, 3], [5, -2]]) # Define coefficients and constants
b = np.array([8, -7])

solution = np.linalg.solve(a, b) # Solve the linear equation
print("Solution:" +"\n", solution)

x = solution[0]
y = solution[1]

print(f"x = {x}, y = {y}")

Solution:
 [-0.26315789  2.84210526]
x = -0.2631578947368419, y = 2.842105263157895


In [10]:
# Sdandarize a array
z = np.random.randint(1,100,25)
print(z)

# Calculate mean and standard deviation
mean = np.mean(z)
std_dev = np.std(z)

# Standardize the array
standardized_arr = (z - mean) / std_dev

print("\nMean:", mean)
print("Standard Deviation:", std_dev)
print("\nStandardized Array:")
print(standardized_arr)

[43 36 42 44 78 56 39 57 99 20 63 42 51 25 68 88 86 60 15 15 22 24 50 20
 40]

Mean: 47.32
Standard Deviation: 23.14254955703887

Standardized Array:
[-0.18666915 -0.4891423  -0.2298796  -0.1434587   1.32569663  0.37506671
 -0.35951095  0.41827716  2.2331161  -1.18050952  0.67753987 -0.2298796
  0.15901446 -0.96445726  0.89359212  1.75780114  1.67138024  0.54790852
 -1.39656177 -1.39656177 -1.09408862 -1.00766771  0.11580401 -1.18050952
 -0.3163005 ]


In [12]:
# Bin Count

arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4,5]) # Create an array of non-negative integers

# Calculate bin counts
bin_counts = np.bincount(arr)

print("Original Array:", arr)
print("Bin Counts:", bin_counts)

Original Array: [1 2 2 3 3 3 4 4 4 4 5]
Bin Counts: [0 1 2 3 4 1]


In [13]:
#Iterating Over Array
a = np.arange(0,60,5).reshape(3,4)
print(a)

for x in np.nditer(a): # It is an efficient multidimensional iterator object using which helps to iterate over an array.
   print(x,end=" ")

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

In [ ]:
# Broadcasting

x = np.array([[1], [2], [3]]) 
y = np.array([4, 5, 6])  
   
# to broadcast x against y 
b = np.broadcast(x,y)  
# it has an iterator property, a tuple of iterators along self's "components." 

for a in b:
    print(a,end=" ")

In [14]:
# Broadcasting

z = np.arange(4).reshape(1,4) 
print(a)
print("\n" + "*" * 15 + "\n") # Cosmetics
print(np.broadcast_to(a,(4,4))) # numpy.broadcast_to(array, shape, subok)

[[0 1 2 3]]

***************

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [ ]:
# Broadcasting

a = np.array([[1, 2, 3], [4, 5, 6]])

result = a + 10 # Add a scalar to the array

print(result)

In [18]:
# Broadcasting

a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b = np.array([[10, 20]])

result = a + b[:, None]

print(result)

[[[11 22]
  [13 24]]

 [[15 26]
  [17 28]]]
